apiVersion: v1
kind: Secret
metadata:
    name: titus-charts-helm-secrets
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:6OE+AA==,iv:8/XDgtKmRobBmYL1Ngkcwdw2RHwNKnHiUx7UQYVvygE=,tag:c1fmQDGTIHwajcaZh7K7yQ==,type:str]
    name: ENC[AES256_GCM,data:Yo09nYxuI6YTe8Je,iv:LFhsENOM7Rb06tHJlKwRB0D0IGp8cqWK0SXL0sJ0Gdk=,tag:oWPeO3nwrh9BGevLmIht7A==,type:str]
    url: ENC[AES256_GCM,data:jXbpUkmuAD38/8fNOcP+0G5PMRpXQMhXZBPemF5bdhk286viWGj1KQQ=,iv:2630a7qXqaiMIxPE5+gk5GeJgBvd0CRo1po1Fd7JCtQ=,tag:YiZ/9+Cx6nlnaj2va90Axg==,type:str]
sops:
    age:
        - recipient: age13dn2lkjvta2sn7g60l7ctvmr0y9mycvdetpex6d0ld8v642shvqqwfhzs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Skp6dnNXLzUwa3lOUFZR
            U0RUOS94OTAxc2p0cWRUYjlRYVhxSlIwc0dZCmZvOVE5b3R6cXZLOXppUm51UzJ6
            aGxEemFXeUlsbWE3Nzh1cGVYY091RzQKLS0tIHhFbFZQdTJBUUpSQzJwQkxwVDlD
            TnRnaUlFUnkrWjBIaGZkUlRkdEREbkEKsV6o6Ye2Bh8bS7wEt48imPlpp9IddXnZ
            +bHDwn92z22xhfLO19HMmpJFef8kAe34EqtGgnykPBQzQpB8k1h96w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T09:47:09Z"
    mac: ENC[AES256_GCM,data:lCNH8uN6IeZX0v2IcYfN2P5TvAqvxharyOcdHdlWwMit8OyXu7o7ItPglJJOo8l30cXHDxZ+XTRwbKHXTdBviweSocNs7lIkPlU5MBg+0SwPv0pWEuuyiobikC52i1qmXVuXqmmbmSgS7scRzjSLR+xQs1Jzm+MADzhmHEf/rIY=,iv:YH5CVLglEJK4eFvoQckwfpEmlU7heUCVd8fpOJzgXPg=,tag:KxOuZBmjmpYXgE4wX0u9vA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
